"""initial schema

Revision ID: 4f260273f1f7
Revises: 
Create Date: 2026-08-13 17:35:08.538823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f260273f1f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pronunciation_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=120), nullable=False),
    sa.Column('phonetic_spelling', sa.String(length=160), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('example_sentences', sa.JSON(), nullable=False),
    sa.Column('pronunciation_tips', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pronunciation_exercises'))
    )
    op.create_index(op.f('ix_pronunciation_exercises_difficulty'), 'pronunciation_exercises', ['difficulty'], unique=False)
    op.create_index(op.f('ix_pronunciation_exercises_id'), 'pronunciation_exercises', ['id'], unique=False)
    op.create_index(op.f('ix_pronunciation_exercises_word'), 'pronunciation_exercises', ['word'], unique=True)
    op.create_table('speaking_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('suggested_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('focus_area', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_challenges'))
    )
    op.create_index(op.f('ix_speaking_challenges_difficulty'), 'speaking_challenges', ['difficulty'], unique=False)
    op.create_index(op.f('ix_speaking_challenges_id'), 'speaking_challenges', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('learning_goal', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password_reset_token_hash', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('response_length_preference', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('public_profile_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_public_profile_visible'), 'users', ['public_profile_visible'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('achievement_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('achievement_key', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_achievement_awards_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievement_awards')),
    sa.UniqueConstraint('session_id', 'user_id', 'achievement_key', name='uq_achievement_award_identity')
    )
    op.create_index(op.f('ix_achievement_awards_achievement_key'), 'achievement_awards', ['achievement_key'], unique=False)
    op.create_index(op.f('ix_achievement_awards_category'), 'achievement_awards', ['category'], unique=False)
    op.create_index(op.f('ix_achievement_awards_id'), 'achievement_awards', ['id'], unique=False)
    op.create_index(op.f('ix_achievement_awards_session_id'), 'achievement_awards', ['session_id'], unique=False)
    op.create_index(op.f('ix_achievement_awards_user_id'), 'achievement_awards', ['user_id'], unique=False)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name=op.f('fk_admin_audit_logs_admin_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit_logs'))
    )
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_admin_user_id'), 'admin_audit_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_target_id'), 'admin_audit_logs', ['target_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('learning_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('issue_key', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=180), nullable=False),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_issues_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_issues')),
    sa.UniqueConstraint('user_id', 'session_id', 'category', 'issue_key', name='uq_learning_issue_identity')
    )
    op.create_index(op.f('ix_learning_issues_category'), 'learning_issues', ['category'], unique=False)
    op.create_index(op.f('ix_learning_issues_id'), 'learning_issues', ['id'], unique=False)
    op.create_index(op.f('ix_learning_issues_issue_key'), 'learning_issues', ['issue_key'], unique=False)
    op.create_index(op.f('ix_learning_issues_session_id'), 'learning_issues', ['session_id'], unique=False)
    op.create_index(op.f('ix_learning_issues_user_id'), 'learning_issues', ['user_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.String(length=120), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('badge', sa.String(length=160), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lesson_progress_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_progress')),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_lesson_progress_user_lesson')
    )
    op.create_index(op.f('ix_lesson_progress_id'), 'lesson_progress', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_lesson_id'), 'lesson_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_user_id'), 'lesson_progress', ['user_id'], unique=False)
    op.create_table('placement_assessment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('skill_scores', sa.JSON(), nullable=True),
    sa.Column('proficiency_level', sa.String(length=32), nullable=True),
    sa.Column('learning_plan', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_placement_assessment_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_assessment_sessions'))
    )
    op.create_index(op.f('ix_placement_assessment_sessions_id'), 'placement_assessment_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_placement_assessment_sessions_proficiency_level'), 'placement_assessment_sessions', ['proficiency_level'], unique=False)
    op.create_index(op.f('ix_placement_assessment_sessions_session_id'), 'placement_assessment_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_placement_assessment_sessions_status'), 'placement_assessment_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_placement_assessment_sessions_user_id'), 'placement_assessment_sessions', ['user_id'], unique=False)
    op.create_table('practice_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('receiver_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['users.id'], name=op.f('fk_practice_requests_receiver_user_id_users')),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('fk_practice_requests_sender_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_requests'))
    )
    op.create_index(op.f('ix_practice_requests_created_at'), 'practice_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_practice_requests_id'), 'practice_requests', ['id'], unique=False)
    op.create_index(op.f('ix_practice_requests_receiver_user_id'), 'practice_requests', ['receiver_user_id'], unique=False)
    op.create_index(op.f('ix_practice_requests_sender_user_id'), 'practice_requests', ['sender_user_id'], unique=False)
    op.create_index(op.f('ix_practice_requests_status'), 'practice_requests', ['status'], unique=False)
    op.create_table('pronunciation_practice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_word_count', sa.Integer(), nullable=False),
    sa.Column('current_word_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pronunciation_practice_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pronunciation_practice_sessions'))
    )
    op.create_index(op.f('ix_pronunciation_practice_sessions_client_session_id'), 'pronunciation_practice_sessions', ['client_session_id'], unique=False)
    op.create_index(op.f('ix_pronunciation_practice_sessions_id'), 'pronunciation_practice_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_pronunciation_practice_sessions_status'), 'pronunciation_practice_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_pronunciation_practice_sessions_user_id'), 'pronunciation_practice_sessions', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_token_id', sa.Integer(), nullable=True),
    sa.Column('reuse_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_revoked_at'), 'refresh_tokens', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_token_jti'), 'refresh_tokens', ['token_jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('retention_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('freeze_tokens', sa.Integer(), nullable=False),
    sa.Column('last_checkin_date', sa.Date(), nullable=True),
    sa.Column('last_freeze_earned_date', sa.Date(), nullable=True),
    sa.Column('last_freeze_used_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_retention_states_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_states')),
    sa.UniqueConstraint('user_id', name='uq_retention_states_user')
    )
    op.create_index(op.f('ix_retention_states_id'), 'retention_states', ['id'], unique=False)
    op.create_index(op.f('ix_retention_states_user_id'), 'retention_states', ['user_id'], unique=False)
    op.create_table('speaking_challenge_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('client_session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('challenge_date', sa.Date(), nullable=False),
    sa.Column('spoken_seconds', sa.Integer(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['speaking_challenges.id'], name=op.f('fk_speaking_challenge_completions_challenge_id_speaking_challenges')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_speaking_challenge_completions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_challenge_completions')),
    sa.UniqueConstraint('client_session_id', 'user_id', 'challenge_date', 'difficulty', name='uq_speaking_completion_daily')
    )
    op.create_index(op.f('ix_speaking_challenge_completions_challenge_date'), 'speaking_challenge_completions', ['challenge_date'], unique=False)
    op.create_index(op.f('ix_speaking_challenge_completions_challenge_id'), 'speaking_challenge_completions', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_speaking_challenge_completions_client_session_id'), 'speaking_challenge_completions', ['client_session_id'], unique=False)
    op.create_index(op.f('ix_speaking_challenge_completions_difficulty'), 'speaking_challenge_completions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_speaking_challenge_completions_id'), 'speaking_challenge_completions', ['id'], unique=False)
    op.create_index(op.f('ix_speaking_challenge_completions_user_id'), 'speaking_challenge_completions', ['user_id'], unique=False)
    op.create_table('speaking_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('grammar_score', sa.Integer(), nullable=False),
    sa.Column('fluency_score', sa.Integer(), nullable=False),
    sa.Column('vocabulary_score', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('coach_feedback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_speaking_evaluations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_evaluations'))
    )
    op.create_index(op.f('ix_speaking_evaluations_created_at'), 'speaking_evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_speaking_evaluations_id'), 'speaking_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_speaking_evaluations_user_id'), 'speaking_evaluations', ['user_id'], unique=False)
    op.create_table('speaking_partner_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('speaking_level', sa.String(length=32), nullable=False),
    sa.Column('native_language', sa.String(length=80), nullable=False),
    sa.Column('target_language', sa.String(length=80), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('availability', sa.JSON(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_speaking_partner_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaking_partner_profiles')),
    sa.UniqueConstraint('user_id', name='uq_speaking_partner_profiles_user_id')
    )
    op.create_index(op.f('ix_speaking_partner_profiles_id'), 'speaking_partner_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_speaking_partner_profiles_is_public'), 'speaking_partner_profiles', ['is_public'], unique=False)
    op.create_index(op.f('ix_speaking_partner_profiles_native_language'), 'speaking_partner_profiles', ['native_language'], unique=False)
    op.create_index(op.f('ix_speaking_partner_profiles_speaking_level'), 'speaking_partner_profiles', ['speaking_level'], unique=False)
    op.create_index(op.f('ix_speaking_partner_profiles_target_language'), 'speaking_partner_profiles', ['target_language'], unique=False)
    op.create_index(op.f('ix_speaking_partner_profiles_timezone'), 'speaking_partner_profiles', ['timezone'], unique=False)
    op.create_index(op.f('ix_speaking_partner_profiles_user_id'), 'speaking_partner_profiles', ['user_id'], unique=False)
    op.create_table('vocabulary_review_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_limit', sa.Integer(), nullable=False),
    sa.Column('due_count', sa.Integer(), nullable=False),
    sa.Column('reviewed_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vocabulary_review_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_review_sessions'))
    )
    op.create_index(op.f('ix_vocabulary_review_sessions_id'), 'vocabulary_review_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_vocabulary_review_sessions_session_id'), 'vocabulary_review_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_review_sessions_status'), 'vocabulary_review_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_vocabulary_review_sessions_user_id'), 'vocabulary_review_sessions', ['user_id'], unique=False)
    op.create_table('conversation_scenario_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('scenario_key', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('target_steps', sa.Integer(), nullable=False),
    sa.Column('scenario_context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_scenario_sessions_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_scenario_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_scenario_sessions'))
    )
    op.create_index(op.f('ix_conversation_scenario_sessions_category'), 'conversation_scenario_sessions', ['category'], unique=False)
    op.create_index(op.f('ix_conversation_scenario_sessions_conversation_id'), 'conversation_scenario_sessions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_scenario_sessions_difficulty'), 'conversation_scenario_sessions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_conversation_scenario_sessions_id'), 'conversation_scenario_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_scenario_sessions_scenario_key'), 'conversation_scenario_sessions', ['scenario_key'], unique=False)
    op.create_index(op.f('ix_conversation_scenario_sessions_session_id'), 'conversation_scenario_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_scenario_sessions_status'), 'conversation_scenario_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_conversation_scenario_sessions_user_id'), 'conversation_scenario_sessions', ['user_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('salience_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_memories_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memories'))
    )
    op.create_index(op.f('ix_memories_conversation_id'), 'memories', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_memories_id'), 'memories', ['id'], unique=False)
    op.create_index(op.f('ix_memories_key'), 'memories', ['key'], unique=False)
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_table('memory_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('salience_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_memory_summaries_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memory_summaries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_summaries'))
    )
    op.create_index(op.f('ix_memory_summaries_conversation_id'), 'memory_summaries', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_memory_summaries_id'), 'memory_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_memory_summaries_user_id'), 'memory_summaries', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_messages_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('placement_assessment_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('skill', sa.String(length=64), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_session_id'], ['placement_assessment_sessions.id'], name=op.f('fk_placement_assessment_answers_assessment_session_id_placement_assessment_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_assessment_answers'))
    )
    op.create_index(op.f('ix_placement_assessment_answers_assessment_session_id'), 'placement_assessment_answers', ['assessment_session_id'], unique=False)
    op.create_index(op.f('ix_placement_assessment_answers_id'), 'placement_assessment_answers', ['id'], unique=False)
    op.create_index(op.f('ix_placement_assessment_answers_question_id'), 'placement_assessment_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_placement_assessment_answers_skill'), 'placement_assessment_answers', ['skill'], unique=False)
    op.create_table('practice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_user_id', sa.Integer(), nullable=False),
    sa.Column('partner_user_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=180), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('feedback_requester', sa.Text(), nullable=False),
    sa.Column('feedback_partner', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['partner_user_id'], ['users.id'], name=op.f('fk_practice_sessions_partner_user_id_users')),
    sa.ForeignKeyConstraint(['request_id'], ['practice_requests.id'], name=op.f('fk_practice_sessions_request_id_practice_requests')),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], name=op.f('fk_practice_sessions_requester_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_sessions'))
    )
    op.create_index(op.f('ix_practice_sessions_id'), 'practice_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_partner_user_id'), 'practice_sessions', ['partner_user_id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_request_id'), 'practice_sessions', ['request_id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_requester_user_id'), 'practice_sessions', ['requester_user_id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_scheduled_at'), 'practice_sessions', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_practice_sessions_status'), 'practice_sessions', ['status'], unique=False)
    op.create_table('pronunciation_practice_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recorded_audio_url', sa.String(length=500), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scoring_status', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['pronunciation_exercises.id'], name=op.f('fk_pronunciation_practice_attempts_exercise_id_pronunciation_exercises')),
    sa.ForeignKeyConstraint(['practice_session_id'], ['pronunciation_practice_sessions.id'], name=op.f('fk_pronunciation_practice_attempts_practice_session_id_pronunciation_practice_sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pronunciation_practice_attempts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pronunciation_practice_attempts'))
    )
    op.create_index(op.f('ix_pronunciation_practice_attempts_exercise_id'), 'pronunciation_practice_attempts', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_pronunciation_practice_attempts_id'), 'pronunciation_practice_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_pronunciation_practice_attempts_practice_session_id'), 'pronunciation_practice_attempts', ['practice_session_id'], unique=False)
    op.create_index(op.f('ix_pronunciation_practice_attempts_scoring_status'), 'pronunciation_practice_attempts', ['scoring_status'], unique=False)
    op.create_index(op.f('ix_pronunciation_practice_attempts_user_id'), 'pronunciation_practice_attempts', ['user_id'], unique=False)
    op.create_table('conversation_scenario_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_session_id', sa.Integer(), nullable=False),
    sa.Column('user_message_id', sa.Integer(), nullable=True),
    sa.Column('assistant_message_id', sa.Integer(), nullable=True),
    sa.Column('user_text', sa.Text(), nullable=False),
    sa.Column('assistant_text', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['messages.id'], name=op.f('fk_conversation_scenario_turns_assistant_message_id_messages')),
    sa.ForeignKeyConstraint(['scenario_session_id'], ['conversation_scenario_sessions.id'], name=op.f('fk_conversation_scenario_turns_scenario_session_id_conversation_scenario_sessions')),
    sa.ForeignKeyConstraint(['user_message_id'], ['messages.id'], name=op.f('fk_conversation_scenario_turns_user_message_id_messages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_scenario_turns'))
    )
    op.create_index(op.f('ix_conversation_scenario_turns_assistant_message_id'), 'conversation_scenario_turns', ['assistant_message_id'], unique=False)
    op.create_index(op.f('ix_conversation_scenario_turns_id'), 'conversation_scenario_turns', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_scenario_turns_scenario_session_id'), 'conversation_scenario_turns', ['scenario_session_id'], unique=False)
    op.create_index(op.f('ix_conversation_scenario_turns_user_message_id'), 'conversation_scenario_turns', ['user_message_id'], unique=False)
    op.create_table('partner_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_user_id'], ['users.id'], name=op.f('fk_partner_reviews_reviewed_user_id_users')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_partner_reviews_reviewer_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], name=op.f('fk_partner_reviews_session_id_practice_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_reviews')),
    sa.UniqueConstraint('session_id', 'reviewer_id', name='uq_partner_reviews_session_reviewer')
    )
    op.create_index(op.f('ix_partner_reviews_created_at'), 'partner_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_partner_reviews_id'), 'partner_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_partner_reviews_reviewed_user_id'), 'partner_reviews', ['reviewed_user_id'], unique=False)
    op.create_index(op.f('ix_partner_reviews_reviewer_id'), 'partner_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_partner_reviews_session_id'), 'partner_reviews', ['session_id'], unique=False)
    op.create_table('practice_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], name=op.f('fk_practice_rooms_session_id_practice_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_rooms'))
    )
    op.create_index(op.f('ix_practice_rooms_id'), 'practice_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_practice_rooms_room_code'), 'practice_rooms', ['room_code'], unique=True)
    op.create_index(op.f('ix_practice_rooms_session_id'), 'practice_rooms', ['session_id'], unique=False)
    op.create_index(op.f('ix_practice_rooms_status'), 'practice_rooms', ['status'], unique=False)
    op.create_table('vocabulary_notebook_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=120), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('example_sentence', sa.Text(), nullable=False),
    sa.Column('mastery_status', sa.String(length=32), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('retention_score', sa.Float(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('review_interval_days', sa.Integer(), nullable=False),
    sa.Column('consecutive_correct', sa.Integer(), nullable=False),
    sa.Column('times_reviewed', sa.Integer(), nullable=False),
    sa.Column('correct_review_count', sa.Integer(), nullable=False),
    sa.Column('bookmarked', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], name=op.f('fk_vocabulary_notebook_entries_source_message_id_messages')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vocabulary_notebook_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_notebook_entries')),
    sa.UniqueConstraint('session_id', 'user_id', 'word', name='uq_vocabulary_notebook_word')
    )
    op.create_index(op.f('ix_vocabulary_notebook_entries_bookmarked'), 'vocabulary_notebook_entries', ['bookmarked'], unique=False)
    op.create_index(op.f('ix_vocabulary_notebook_entries_id'), 'vocabulary_notebook_entries', ['id'], unique=False)
    op.create_index(op.f('ix_vocabulary_notebook_entries_mastery_status'), 'vocabulary_notebook_entries', ['mastery_status'], unique=False)
    op.create_index(op.f('ix_vocabulary_notebook_entries_review_date'), 'vocabulary_notebook_entries', ['review_date'], unique=False)
    op.create_index(op.f('ix_vocabulary_notebook_entries_session_id'), 'vocabulary_notebook_entries', ['session_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_notebook_entries_source_message_id'), 'vocabulary_notebook_entries', ['source_message_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_notebook_entries_user_id'), 'vocabulary_notebook_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_notebook_entries_word'), 'vocabulary_notebook_entries', ['word'], unique=False)
    op.create_table('practice_room_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['practice_rooms.id'], name=op.f('fk_practice_room_messages_room_id_practice_rooms')),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('fk_practice_room_messages_sender_user_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], name=op.f('fk_practice_room_messages_session_id_practice_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_room_messages'))
    )
    op.create_index(op.f('ix_practice_room_messages_created_at'), 'practice_room_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_practice_room_messages_id'), 'practice_room_messages', ['id'], unique=False)
    op.create_index(op.f('ix_practice_room_messages_message_type'), 'practice_room_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_practice_room_messages_room_id'), 'practice_room_messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_practice_room_messages_sender_user_id'), 'practice_room_messages', ['sender_user_id'], unique=False)
    op.create_index(op.f('ix_practice_room_messages_session_id'), 'practice_room_messages', ['session_id'], unique=False)
    op.create_table('vocabulary_review_session_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_session_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('recall_quality', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['vocabulary_notebook_entries.id'], name=op.f('fk_vocabulary_review_session_items_entry_id_vocabulary_notebook_entries')),
    sa.ForeignKeyConstraint(['review_session_id'], ['vocabulary_review_sessions.id'], name=op.f('fk_vocabulary_review_session_items_review_session_id_vocabulary_review_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_review_session_items')),
    sa.UniqueConstraint('review_session_id', 'entry_id', name='uq_vocabulary_review_session_item')
    )
    op.create_index(op.f('ix_vocabulary_review_session_items_entry_id'), 'vocabulary_review_session_items', ['entry_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_review_session_items_id'), 'vocabulary_review_session_items', ['id'], unique=False)
    op.create_index(op.f('ix_vocabulary_review_session_items_review_session_id'), 'vocabulary_review_session_items', ['review_session_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_review_session_items_status'), 'vocabulary_review_session_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_review_session_items_status'), table_name='vocabulary_review_session_items')
    op.drop_index(op.f('ix_vocabulary_review_session_items_review_session_id'), table_name='vocabulary_review_session_items')
    op.drop_index(op.f('ix_vocabulary_review_session_items_id'), table_name='vocabulary_review_session_items')
    op.drop_index(op.f('ix_vocabulary_review_session_items_entry_id'), table_name='vocabulary_review_session_items')
    op.drop_table('vocabulary_review_session_items')
    op.drop_index(op.f('ix_practice_room_messages_session_id'), table_name='practice_room_messages')
    op.drop_index(op.f('ix_practice_room_messages_sender_user_id'), table_name='practice_room_messages')
    op.drop_index(op.f('ix_practice_room_messages_room_id'), table_name='practice_room_messages')
    op.drop_index(op.f('ix_practice_room_messages_message_type'), table_name='practice_room_messages')
    op.drop_index(op.f('ix_practice_room_messages_id'), table_name='practice_room_messages')
    op.drop_index(op.f('ix_practice_room_messages_created_at'), table_name='practice_room_messages')
    op.drop_table('practice_room_messages')
    op.drop_index(op.f('ix_vocabulary_notebook_entries_word'), table_name='vocabulary_notebook_entries')
    op.drop_index(op.f('ix_vocabulary_notebook_entries_user_id'), table_name='vocabulary_notebook_entries')
    op.drop_index(op.f('ix_vocabulary_notebook_entries_source_message_id'), table_name='vocabulary_notebook_entries')
    op.drop_index(op.f('ix_vocabulary_notebook_entries_session_id'), table_name='vocabulary_notebook_entries')
    op.drop_index(op.f('ix_vocabulary_notebook_entries_review_date'), table_name='vocabulary_notebook_entries')
    op.drop_index(op.f('ix_vocabulary_notebook_entries_mastery_status'), table_name='vocabulary_notebook_entries')
    op.drop_index(op.f('ix_vocabulary_notebook_entries_id'), table_name='vocabulary_notebook_entries')
    op.drop_index(op.f('ix_vocabulary_notebook_entries_bookmarked'), table_name='vocabulary_notebook_entries')
    op.drop_table('vocabulary_notebook_entries')
    op.drop_index(op.f('ix_practice_rooms_status'), table_name='practice_rooms')
    op.drop_index(op.f('ix_practice_rooms_session_id'), table_name='practice_rooms')
    op.drop_index(op.f('ix_practice_rooms_room_code'), table_name='practice_rooms')
    op.drop_index(op.f('ix_practice_rooms_id'), table_name='practice_rooms')
    op.drop_table('practice_rooms')
    op.drop_index(op.f('ix_partner_reviews_session_id'), table_name='partner_reviews')
    op.drop_index(op.f('ix_partner_reviews_reviewer_id'), table_name='partner_reviews')
    op.drop_index(op.f('ix_partner_reviews_reviewed_user_id'), table_name='partner_reviews')
    op.drop_index(op.f('ix_partner_reviews_id'), table_name='partner_reviews')
    op.drop_index(op.f('ix_partner_reviews_created_at'), table_name='partner_reviews')
    op.drop_table('partner_reviews')
    op.drop_index(op.f('ix_conversation_scenario_turns_user_message_id'), table_name='conversation_scenario_turns')
    op.drop_index(op.f('ix_conversation_scenario_turns_scenario_session_id'), table_name='conversation_scenario_turns')
    op.drop_index(op.f('ix_conversation_scenario_turns_id'), table_name='conversation_scenario_turns')
    op.drop_index(op.f('ix_conversation_scenario_turns_assistant_message_id'), table_name='conversation_scenario_turns')
    op.drop_table('conversation_scenario_turns')
    op.drop_index(op.f('ix_pronunciation_practice_attempts_user_id'), table_name='pronunciation_practice_attempts')
    op.drop_index(op.f('ix_pronunciation_practice_attempts_scoring_status'), table_name='pronunciation_practice_attempts')
    op.drop_index(op.f('ix_pronunciation_practice_attempts_practice_session_id'), table_name='pronunciation_practice_attempts')
    op.drop_index(op.f('ix_pronunciation_practice_attempts_id'), table_name='pronunciation_practice_attempts')
    op.drop_index(op.f('ix_pronunciation_practice_attempts_exercise_id'), table_name='pronunciation_practice_attempts')
    op.drop_table('pronunciation_practice_attempts')
    op.drop_index(op.f('ix_practice_sessions_status'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_scheduled_at'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_requester_user_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_request_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_partner_user_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_id'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    op.drop_index(op.f('ix_placement_assessment_answers_skill'), table_name='placement_assessment_answers')
    op.drop_index(op.f('ix_placement_assessment_answers_question_id'), table_name='placement_assessment_answers')
    op.drop_index(op.f('ix_placement_assessment_answers_id'), table_name='placement_assessment_answers')
    op.drop_index(op.f('ix_placement_assessment_answers_assessment_session_id'), table_name='placement_assessment_answers')
    op.drop_table('placement_assessment_answers')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_memory_summaries_user_id'), table_name='memory_summaries')
    op.drop_index(op.f('ix_memory_summaries_id'), table_name='memory_summaries')
    op.drop_index(op.f('ix_memory_summaries_conversation_id'), table_name='memory_summaries')
    op.drop_table('memory_summaries')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_key'), table_name='memories')
    op.drop_index(op.f('ix_memories_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_conversation_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_conversation_scenario_sessions_user_id'), table_name='conversation_scenario_sessions')
    op.drop_index(op.f('ix_conversation_scenario_sessions_status'), table_name='conversation_scenario_sessions')
    op.drop_index(op.f('ix_conversation_scenario_sessions_session_id'), table_name='conversation_scenario_sessions')
    op.drop_index(op.f('ix_conversation_scenario_sessions_scenario_key'), table_name='conversation_scenario_sessions')
    op.drop_index(op.f('ix_conversation_scenario_sessions_id'), table_name='conversation_scenario_sessions')
    op.drop_index(op.f('ix_conversation_scenario_sessions_difficulty'), table_name='conversation_scenario_sessions')
    op.drop_index(op.f('ix_conversation_scenario_sessions_conversation_id'), table_name='conversation_scenario_sessions')
    op.drop_index(op.f('ix_conversation_scenario_sessions_category'), table_name='conversation_scenario_sessions')
    op.drop_table('conversation_scenario_sessions')
    op.drop_index(op.f('ix_vocabulary_review_sessions_user_id'), table_name='vocabulary_review_sessions')
    op.drop_index(op.f('ix_vocabulary_review_sessions_status'), table_name='vocabulary_review_sessions')
    op.drop_index(op.f('ix_vocabulary_review_sessions_session_id'), table_name='vocabulary_review_sessions')
    op.drop_index(op.f('ix_vocabulary_review_sessions_id'), table_name='vocabulary_review_sessions')
    op.drop_table('vocabulary_review_sessions')
    op.drop_index(op.f('ix_speaking_partner_profiles_user_id'), table_name='speaking_partner_profiles')
    op.drop_index(op.f('ix_speaking_partner_profiles_timezone'), table_name='speaking_partner_profiles')
    op.drop_index(op.f('ix_speaking_partner_profiles_target_language'), table_name='speaking_partner_profiles')
    op.drop_index(op.f('ix_speaking_partner_profiles_speaking_level'), table_name='speaking_partner_profiles')
    op.drop_index(op.f('ix_speaking_partner_profiles_native_language'), table_name='speaking_partner_profiles')
    op.drop_index(op.f('ix_speaking_partner_profiles_is_public'), table_name='speaking_partner_profiles')
    op.drop_index(op.f('ix_speaking_partner_profiles_id'), table_name='speaking_partner_profiles')
    op.drop_table('speaking_partner_profiles')
    op.drop_index(op.f('ix_speaking_evaluations_user_id'), table_name='speaking_evaluations')
    op.drop_index(op.f('ix_speaking_evaluations_id'), table_name='speaking_evaluations')
    op.drop_index(op.f('ix_speaking_evaluations_created_at'), table_name='speaking_evaluations')
    op.drop_table('speaking_evaluations')
    op.drop_index(op.f('ix_speaking_challenge_completions_user_id'), table_name='speaking_challenge_completions')
    op.drop_index(op.f('ix_speaking_challenge_completions_id'), table_name='speaking_challenge_completions')
    op.drop_index(op.f('ix_speaking_challenge_completions_difficulty'), table_name='speaking_challenge_completions')
    op.drop_index(op.f('ix_speaking_challenge_completions_client_session_id'), table_name='speaking_challenge_completions')
    op.drop_index(op.f('ix_speaking_challenge_completions_challenge_id'), table_name='speaking_challenge_completions')
    op.drop_index(op.f('ix_speaking_challenge_completions_challenge_date'), table_name='speaking_challenge_completions')
    op.drop_table('speaking_challenge_completions')
    op.drop_index(op.f('ix_retention_states_user_id'), table_name='retention_states')
    op.drop_index(op.f('ix_retention_states_id'), table_name='retention_states')
    op.drop_table('retention_states')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_pronunciation_practice_sessions_user_id'), table_name='pronunciation_practice_sessions')
    op.drop_index(op.f('ix_pronunciation_practice_sessions_status'), table_name='pronunciation_practice_sessions')
    op.drop_index(op.f('ix_pronunciation_practice_sessions_id'), table_name='pronunciation_practice_sessions')
    op.drop_index(op.f('ix_pronunciation_practice_sessions_client_session_id'), table_name='pronunciation_practice_sessions')
    op.drop_table('pronunciation_practice_sessions')
    op.drop_index(op.f('ix_practice_requests_status'), table_name='practice_requests')
    op.drop_index(op.f('ix_practice_requests_sender_user_id'), table_name='practice_requests')
    op.drop_index(op.f('ix_practice_requests_receiver_user_id'), table_name='practice_requests')
    op.drop_index(op.f('ix_practice_requests_id'), table_name='practice_requests')
    op.drop_index(op.f('ix_practice_requests_created_at'), table_name='practice_requests')
    op.drop_table('practice_requests')
    op.drop_index(op.f('ix_placement_assessment_sessions_user_id'), table_name='placement_assessment_sessions')
    op.drop_index(op.f('ix_placement_assessment_sessions_status'), table_name='placement_assessment_sessions')
    op.drop_index(op.f('ix_placement_assessment_sessions_session_id'), table_name='placement_assessment_sessions')
    op.drop_index(op.f('ix_placement_assessment_sessions_proficiency_level'), table_name='placement_assessment_sessions')
    op.drop_index(op.f('ix_placement_assessment_sessions_id'), table_name='placement_assessment_sessions')
    op.drop_table('placement_assessment_sessions')
    op.drop_index(op.f('ix_lesson_progress_user_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_lesson_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_learning_issues_user_id'), table_name='learning_issues')
    op.drop_index(op.f('ix_learning_issues_session_id'), table_name='learning_issues')
    op.drop_index(op.f('ix_learning_issues_issue_key'), table_name='learning_issues')
    op.drop_index(op.f('ix_learning_issues_id'), table_name='learning_issues')
    op.drop_index(op.f('ix_learning_issues_category'), table_name='learning_issues')
    op.drop_table('learning_issues')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_admin_audit_logs_target_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_created_at'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_user_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_achievement_awards_user_id'), table_name='achievement_awards')
    op.drop_index(op.f('ix_achievement_awards_session_id'), table_name='achievement_awards')
    op.drop_index(op.f('ix_achievement_awards_id'), table_name='achievement_awards')
    op.drop_index(op.f('ix_achievement_awards_category'), table_name='achievement_awards')
    op.drop_index(op.f('ix_achievement_awards_achievement_key'), table_name='achievement_awards')
    op.drop_table('achievement_awards')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_public_profile_visible'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_speaking_challenges_id'), table_name='speaking_challenges')
    op.drop_index(op.f('ix_speaking_challenges_difficulty'), table_name='speaking_challenges')
    op.drop_table('speaking_challenges')
    op.drop_index(op.f('ix_pronunciation_exercises_word'), table_name='pronunciation_exercises')
    op.drop_index(op.f('ix_pronunciation_exercises_id'), table_name='pronunciation_exercises')
    op.drop_index(op.f('ix_pronunciation_exercises_difficulty'), table_name='pronunciation_exercises')
    op.drop_table('pronunciation_exercises')
    # ### end Alembic commands ###
